#!/usr/bin/env python3
"""Materialize the model/ snapshot from the project's own model code.

Single source that (re)generates every file under model/ from the pinned
submodules (third_party/car + third_party/attack-datasources) via the SAME code
the pipeline runs — nothing here re-implements the schema:

    model/car/objects/<object>.yml   one file per CAR object (13): the common
                                     store header + the object's MITRE CAR fields
                                     (descriptions/examples from the CAR model),
                                     plus its superset car_action list.
    model/superset/model-objects.yml       the CAR+ATT&CK object catalogue (~38)
    model/superset/relationship-types.yml  the ATT&CK relationship vocabulary (~243)
    model/superset/relationship-schema.yml the relationship-instance row shape
                                     (from byakugan.superset.REL_COLUMNS directly —
                                     the engine holds this in memory, not SQLite)
    model/spindle/identity.yml       the spindle row-identity registry (byakugan/
                                     spindle.yml) resolved against the live maps + ids.py
    model/spindle/record.yml         the shape of a spindle — a minted-identity CAR row
    model/spindle/golden.yml         the golden vectors: per entry the key + guid the engine
                                     mints for its sample; the positional and recipe vectors
    model/relationships/declared.yml the DECLARED relationship model, readable: per object
                                     the owner-edge verb per action (typing-tiered against the
                                     pinned ATT&CK catalogue), the special edges, and the
                                     association properties each edge carries — rendered from
                                     byakugan/cascade_relationships.yml
    model/relationships/derived.yml  the DERIVED relationship model, readable: the strong
                                     identities, 1:1 links and reconstruction rules — rendered
                                     from byakugan/relationships.yml `derived:`

The sources of truth are the pinned submodules (and, for model/spindle/, the
hand-authored registry byakugan/spindle.yml + the maps); a model refresh
is a submodule pin bump — or a registry / map change — after which re-running
this script re-materializes model/ deterministically.

    python model/generate.py
"""
from __future__ import annotations

import glob
import os
import re
import subprocess
import sys

import yaml

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
# Import the project's own model code (works installed or from a bare checkout).
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from byakugan import build_data_model, carmodel, spindle, store, superset  # noqa: E402

_CAR_DM = os.path.join(_ROOT, "third_party", "car", "data_model")

# The 13 CAR objects, in the canonical order used everywhere else.
CAR_OBJECTS = [
    "authentication", "driver", "email", "file", "flow", "http", "module",
    "process", "registry", "service", "socket", "thread", "user_session",
]


# --------------------------------------------------------------------------- #
# YAML: block style, source order preserved, no anchors/aliases, deterministic.
# --------------------------------------------------------------------------- #
class _Dumper(yaml.SafeDumper):
    def ignore_aliases(self, data):  # never emit &anchors / *aliases
        return True


def _yaml(obj) -> str:
    return yaml.dump(obj, Dumper=_Dumper, sort_keys=False,
                     default_flow_style=False, allow_unicode=True, width=100)


def _write(path: str, header_comment: str, body: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(header_comment)
        fh.write(body)


def _submodule_sha(rel_path: str) -> str:
    try:
        out = subprocess.check_output(
            ["git", "-C", os.path.join(_ROOT, rel_path), "rev-parse", "HEAD"],
            stderr=subprocess.DEVNULL)
        return out.decode().strip()
    except Exception:
        return "<unknown — submodule not checked out>"


CAR_SHA = _submodule_sha("third_party/car")
ADS_SHA = _submodule_sha("third_party/attack-datasources")

_PROVENANCE = (f"# Source of truth (pinned submodules):\n"
               f"#   third_party/car @ {CAR_SHA}\n"
               f"#   third_party/attack-datasources @ {ADS_SHA}\n")


def _car_yaml_header(obj: str) -> str:
    return (f"# GENERATED by `python model/generate.py` — do not edit by hand.\n"
            f"# The `{obj}` CAR object: reconstructed from byakugan.carmodel /\n"
            f"# store.HEADER (properties) and build_data_model.build_superset (car_action),\n"
            f"# enriched with field descriptions from the pinned car data_model/{obj}.yaml.\n"
            f"{_PROVENANCE}\n")


def _superset_yaml_header(what: str) -> str:
    return (f"# GENERATED by `python model/generate.py` — do not edit by hand.\n"
            f"# {what}\n"
            f"# Reconstructed from byakugan.build_data_model / superset.py.\n"
            f"{_PROVENANCE}\n")


# --------------------------------------------------------------------------- #
# Read the raw CAR data_model YAMLs for human descriptions/examples. The field
# LIST + header separation are taken from the project's code (carmodel / store);
# only the prose descriptions come from here (the CAR model is their only source).
# These descriptions/examples are emitted VERBATIM (see model/README.md) and may
# carry upstream typos or imperfect example values; corrections belong upstream.
# --------------------------------------------------------------------------- #
def _load_car_raw() -> dict[str, dict]:
    raw: dict[str, dict] = {}
    for path in sorted(glob.glob(os.path.join(_CAR_DM, "*.yaml"))):
        with open(path, encoding="utf-8") as fh:
            doc = yaml.safe_load(fh)
        key = re.sub(r"[^a-z0-9]+", "_", doc["name"].lower()).strip("_")
        raw[key] = doc
    return raw


def gen_car_objects() -> int:
    raw = _load_car_raw()
    model = carmodel.load()
    sup_model, _ = build_data_model.build_superset()
    sup_actions = {(o["name"][0] if isinstance(o["name"], list) else o["name"]):
                   list(o.get("actions", [])) for o in sup_model["objects"]}

    n = 0
    for obj in CAR_OBJECTS:
        doc = raw.get(obj, {})
        field_desc = {f["name"]: f for f in (doc.get("fields") or [])}

        object_fields = []
        for name in model[obj]["fields"]:
            if name in store.HEADER:  # mirror store._cols: header wins, never dup
                continue
            src = field_desc.get(name, {})
            entry = {"name": name}
            if src.get("description"):
                entry["description"] = str(src["description"]).strip()
            if "example" in src and src["example"] is not None:
                entry["example"] = src["example"]
            object_fields.append(entry)

        out: dict = {"name": obj}
        if doc.get("description"):
            out["description"] = str(doc["description"]).strip()
        # car_action list comes from the superset model_object.actions (CAR
        # actions unioned with any ATT&CK-data-component actions), as the DB seeds it.
        out["car_action"] = sup_actions.get(obj, list(model[obj]["actions"]))
        out["properties"] = {
            # store.HEADER — the common CAR-event header shared by all 13 objects
            # (byakugan/store.py). The CAR model does not describe these.
            "common_header": list(store.HEADER),
            # the object's MITRE CAR fields (third_party/car data_model/<obj>.yaml).
            "object_fields": object_fields,
        }
        _write(os.path.join(_HERE, "car", "objects", f"{obj}.yml"),
               _car_yaml_header(obj), _yaml(out))
        n += 1
    return n


def gen_model_objects() -> int:
    sup_model, _ = build_data_model.build_superset()
    objects = []
    for o in sup_model["objects"]:
        name = o["name"][0] if isinstance(o["name"], list) else o["name"]
        objects.append({
            "name": name,
            "source": o.get("source"),
            "actions": list(o.get("actions", [])),
            "definition": o.get("definition"),
        })
    objects.sort(key=lambda d: d["name"])
    _write(os.path.join(_HERE, "superset", "model-objects.yml"),
           _superset_yaml_header(
               "The CAR + ATT&CK data-sources object catalogue (superset model_object):\n"
               "# name / source (car | attack | car+attack) / actions / definition."),
           _yaml({"model_objects": objects}))
    return len(objects)


def gen_relationship_types() -> int:
    _, rels = build_data_model.build_superset()
    grouped: dict[str, list] = {}
    for r in rels:
        grouped.setdefault(r["source"], []).append(
            {"relationship": r["relationship"], "target": r["target"]})
    ordered = {}
    for src in sorted(grouped):
        ordered[src] = sorted(grouped[src],
                              key=lambda d: (d["relationship"], d["target"]))
    _write(os.path.join(_HERE, "superset", "relationship-types.yml"),
           _superset_yaml_header(
               f"The ATT&CK data-source relationship vocabulary ({len(rels)} edge-types),\n"
               "# grouped by source element: source --relationship--> target. This is the\n"
               "# cascade vocabulary; cascade_relationships.yml maps our joins onto it."),
           _yaml({"relationship_types": ordered}))
    return len(rels)


def gen_relationship_schema() -> None:
    """The relationship-instance row shape, straight from byakugan.superset's
    own authoritative tuple (superset.REL_COLUMNS) — no SQLite, no
    introspection: the engine holds this in memory now, so the column list
    itself IS the schema."""
    cols = [{"name": name} for name in superset.REL_COLUMNS]
    schema = {"relationship_instance": {
        "columns": cols,
        "description": ("One row per materialized edge: a source_object "
                        "--relationship--> target_object instance, timestamped and "
                        "pointing back at the object events by guid. See "
                        "byakugan/superset.py (REL_COLUMNS)."),
    }}
    _write(os.path.join(_HERE, "superset", "relationship-schema.yml"),
           _superset_yaml_header(
               "The relationship-instance row shape (byakugan.superset.SupersetStore),\n"
               "# straight from byakugan.superset.REL_COLUMNS — the authoritative shape."),
           _yaml(schema))


# --------------------------------------------------------------------------- #
# model/relationships/ — the DECLARED + DERIVED relationship model, readable.
# --------------------------------------------------------------------------- #
# CAR object -> the ATT&CK data-element names it corresponds to, for the typing
# tier the rendering carries: an edge is `exact` when its (source element,
# verb, target element) triple exists in the pinned catalogue under this
# aliasing; anything else is `extension` — a catalogue verb applied where
# Byakugan's evidence is finer-grained than ATT&CK's elements
# (docs/research/relationship-model-gaps.md §2). Presentation logic only:
# nothing at runtime reads it.
_ELEMENT_ALIASES = {
    "process": {"process"},
    "file": {"file"},
    "registry": {"windows registry key", "windows registry key value"},
    "module": {"module", "kernel module"},
    "driver": {"driver"},
    "service": {"service"},
    "user_session": {"logon session"},
    "flow": {"network traffic", "network traffic flow", "ip", "port", "host"},
    "socket": {"port"},
    "thread": {"thread"},
    "http": {"web traffic"},
    "user_account": {"user"},
    "authentication": set(),       # CAR-only event object: no ATT&CK element
    "email": set(),                # no ATT&CK element (Application Log at best)
}

# The special edges' endpoints and triggers — mirrors byakugan.superset
# edges_from_events (every branch is exercised by tests/test_superset.py).
_EDGE_SHAPES = {
    "parent_process": ("process", ["process"],
                       "a process/create row's resolved parent_guid"),
    "process_access": ("process", ["process"],
                       "a process/access row's owner -> its target_guid (Sysmon 10)"),
    "thread_injection": ("process", ["process"],
                         "a thread row's owner -> native.target_process_guid (Sysmon 8)"),
    "file_executed": ("process", ["file"],
                      "native.executed_as_process_guid (file_path == image_path, CAR-2014-02-001)"),
    "auth_session": ("authentication", ["user_session"],
                     "native.target_session_guid / subject_session_guid (the LUID join)"),
    "flow_contains": ("flow", ["http", "file"],
                      "native.flow_guid on a zeek spoke (the shared capture uid, R3)"),
    "process_modify": ("process", ["process"],
                       "a process/modify row's native.modifier_process_guid (the declared contract)"),
}

# the process hub's actions, whose relationships are the special edges (or a
# recorded non-edge), never spoke_owner entries
_PROCESS_HUB = {
    "access": {"via_edge": "process_access"},
    "create": {"via_edge": "parent_process"},
    "execute": {"via_edge": "file_executed"},
    "metadata": {"status": "no edge — the user-dimension family "
                           "(relationship-model gap register §3.2.1, decision D3)"},
    "modify": {"via_edge": "process_modify"},
    "terminate": {"status": "no edge — no artefact names the terminator "
                            "(register §3.3, an honest null)"},
}


def _typing(triples: set, s_obj: str, verb: str, t_obj: str) -> str:
    for se in _ELEMENT_ALIASES.get(s_obj, {s_obj}):
        for te in _ELEMENT_ALIASES.get(t_obj, {t_obj}):
            if (se, verb, te) in triples:
                return "exact"
    return "extension"


def _assoc_list(spec: dict) -> dict:
    return {k: (list(v) if isinstance(v, list) else [v]) for k, v in spec.items()}


def _relationships_header(what: str) -> str:
    return (f"# GENERATED by `python model/generate.py` — do not edit by hand.\n"
            f"# {what}\n"
            f"# typing: exact = the (source element, verb, target element) triple exists in the\n"
            f"# pinned ATT&CK catalogue (element aliasing in model/generate.py); extension = a\n"
            f"# catalogue verb applied where Byakugan's evidence is finer-grained than ATT&CK's\n"
            f"# elements (docs/research/relationship-model-gaps.md §2).\n"
            f"{_PROVENANCE}\n")


def gen_relationships() -> tuple[int, int]:
    from byakugan import enrich, superset as sup
    _, rels = build_data_model.build_superset()
    triples = {(x["source"], x["relationship"], x["target"]) for x in rels}
    r = sup.rules()
    spoke, default = r["spoke_owner"], r["default_spoke_verb"]
    assoc = r.get("association_properties") or {}
    model = carmodel.load()

    per_object: dict = {}
    n = 0
    for obj in CAR_OBJECTS:
        entries = []
        for act in model[obj]["actions"]:
            e: dict = {"car_action": act}
            if obj == "process":
                e.update(_PROCESS_HUB.get(act, {"status": "unmapped hub action"}))
            else:
                verb = (spoke.get(obj) or {}).get(act)
                if verb is None:
                    e["relationship"] = None
                    e["status"] = ("decision-flagged (register §9 D1/D2): undeclared, the "
                                   f"default verb {default!r} applies")
                else:
                    e["relationship"] = verb
                    e["form"] = f"process --{verb}--> {obj}"
                    e["typing"] = _typing(triples, "process", verb, obj)
                props = assoc.get(f"{obj}/{act}")
                if props:
                    e["association_properties"] = _assoc_list(props)
            entries.append(e)
            n += 1
        per_object[obj] = entries

    edges = []
    for name, verb in (r.get("edges") or {}).items():
        s_obj, t_objs, trigger = _EDGE_SHAPES[name]
        e = {"name": name, "relationship": verb,
             "form": [f"{s_obj} --{verb}--> {t}" for t in t_objs],
             "typing": {t: _typing(triples, s_obj, verb, t) for t in t_objs},
             "trigger": trigger}
        props = assoc.get(f"edge:{name}")
        if props:
            e["association_properties"] = _assoc_list(props)
        edges.append(e)

    _write(os.path.join(_HERE, "relationships", "declared.yml"),
           _relationships_header(
               "The DECLARED relationship model (class=declared), readable: per CAR object the\n"
               "# owner-edge verb per action, the special edges, and the association properties\n"
               "# each edge carries (facts OF the relationship — the #108 pattern). Rendered from\n"
               "# byakugan/cascade_relationships.yml; the engine is byakugan/superset.py."),
           _yaml({"declared_relationships": {
               "default_spoke_verb": default,
               "spoke_owner": per_object,
               "edges": edges}}))

    d = enrich.rules().get("derived") or {}
    identities = {}
    for iname in sorted(d.get("identities") or {}):
        spec = d["identities"][iname]
        identities[iname] = {k: spec[k] for k in
                             ("kind", "guid_form", "normalize", "accept", "node",
                              "fields", "properties") if k in spec}
    links = []
    for rule in d.get("links") or []:
        links.append({
            "name": rule["name"],
            "form": f"{rule['source']} --{rule['relationship']}--> {rule['target']}",
            "typing": _typing(triples, rule["source"], rule["relationship"], rule["target"]),
            "identity": rule["identity"], "method": rule["method"],
            "confidence": rule.get("confidence", "definitive"),
            **({"join": rule["join"]} if "join" in rule else {}),
            **({"prefer": rule["prefer"]} if "prefer" in rule else {}),
        })
    recon = []
    for rule in d.get("reconstruct") or []:
        verb = rule["relationship"]
        if verb == "spoke_owner":
            form = ("process --<spoke_owner[(object, action)]>--> <spoke> "
                    "(the missing owner takes the spoke's declared verb)")
            typing = "per spoke_owner entry"
        else:
            s_obj = rule["node"] if rule.get("end", "source") == "source" else \
                rule.get("observed", {}).get("object", rule.get("on", "").partition("/")[0])
            t_obj = rule.get("on", "").partition("/")[0] if rule.get("end", "source") == "source" \
                else rule["node"]
            form = f"{s_obj or '<observed>'} --{verb}--> {t_obj or '<observed>'}"
            typing = _typing(triples, s_obj or "", verb, t_obj or "")
        recon.append({
            "name": rule["name"], "on": rule.get("on"), "node": rule["node"],
            "inferred_end": rule.get("end", "source"), "form": form, "typing": typing,
            "identity": rule["identity"], "reference": rule["reference"],
            "unless_linked": rule.get("unless_linked"), "method": rule["method"],
            "properties": rule.get("properties") or {},
        })
    _write(os.path.join(_HERE, "relationships", "derived.yml"),
           _relationships_header(
               "The DERIVED relationship model (class=derived), readable: the strong identities,\n"
               "# the both-ends-observed 1:1 links, and the reconstruction rules whose missing end\n"
               "# becomes a flagged inferred_node. Rendered from byakugan/relationships.yml\n"
               "# `derived:`; the engine is byakugan/derive.py."),
           _yaml({"derived_relationships": {
               "identities": identities, "links": links, "reconstruct": recon}}))
    return n, len(edges)


def gen_spindle() -> int:
    """model/spindle/: the spindle row-identity registry snapshot + the spindle
    record shape — resolved from byakugan/spindle.yml, the live maps and
    ids.py by the SAME code the engine mints with (byakugan.spindle), so
    the snapshot can never describe an identity the pipeline does not mint."""
    problems = spindle.verify_registry()
    if problems:
        raise SystemExit("spindle registry invalid:\n  - " + "\n  - ".join(problems))
    try:
        # the change protocol's gate: an entry's golden guid moves only with its version
        return len(spindle.write_snapshot(os.path.join(_HERE, "spindle")))
    except ValueError as exc:
        raise SystemExit(f"spindle snapshot not written — {exc}") from None


def main() -> int:
    n_car = gen_car_objects()
    n_obj = gen_model_objects()
    n_rel = gen_relationship_types()
    gen_relationship_schema()
    n_pairs, n_edges = gen_relationships()
    n_sp = gen_spindle()
    print(f"model/ materialized: {n_car} CAR object files | "
          f"{n_obj} superset model-objects | {n_rel} relationship-types | "
          f"relationship-schema | declared/derived relationships "
          f"({n_pairs} (object, action) pairs, {n_edges} special edges) | "
          f"{n_sp} spindle files")
    print(f"pins: car @ {CAR_SHA[:12]} | attack-datasources @ {ADS_SHA[:12]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
