// Package conform mirrors the count-and-carry finding record — the ONE shape
// both engines emit (Python reference: byakugan/conform.py; schema:
// model/schema/defs.schema.json#/$defs/finding). Rules register in the layer
// packages as the epic phases land; this package holds only the shared shape
// and tally so Go and Python provably agree on it.
package conform

// Finding is the neutral conformance record: every failure tallies, nothing
// is dropped for being unfamiliar, strict mode fails on a nonzero tally.
type Finding struct {
	ObjectID string `json:"object_id"`
	Rule     string `json:"rule"`
	Message  string `json:"message"`
	Path     string `json:"path,omitempty"`
}

// Tally counts findings per rule id.
func Tally(findings []Finding) map[string]int {
	out := make(map[string]int, len(findings))
	for _, f := range findings {
		out[f.Rule]++
	}
	return out
}

// GoChecks names every Go-side gate the conformance table
// (model/schema/conformance.json) may claim for engine "go". The table is
// generated by the Python side (`python -m byakugan.conform --write-table`);
// TestConformanceTableNamesRealGoChecks holds the two in step, so the table
// can never claim a Go gate that does not exist and a Go gate cannot go
// unlisted — the #136 definition of done, read from BOTH engines.
var GoChecks = map[string]bool{
	"gen-ir-check":        true, // make -C go gen-ir-check
	"registry-against-ir": true, // internal/predicates TestRegistryAgainstIR
	"finding-wire-parity": true, // this package's TestFindingWireShape
}
